module.exports = {
    DefaultUnknown: "צר לי, לא הבנתי אותך. נסה שוב",
    Michrazim1SingleOrMultiple:"האם ברצונך לקבל מידע על מכרז ספציפי?",
    Michrazim1Michraz:"  אנא הזן מספר מכרז בפורמט המבוקש  \n לדוגמה: בש/1/2000 \n להלן חלוקת האזורים : דרום-בש, צפון-צפ, מרכז-מר, ירושלים-ים, חיפה-חי, תל-אביב-תא   ",
    Michrazim3TenderState: "בחר מצב מכרז (פעיל,ארכיון, הכל)",
    Michrazim4Designation: "בחר יעוד",
    Michrazim5Area: "בחר אזור",
    Michrazim6Locality: "אנא הזן שם יישוב",
    Michrazim6LocalityRetry: "לא הצלחתי לזהות את הישוב, אנא הזן שם ישוב",
    Michrazim1MichrazRetry: "לא הצלחתי לזהות את מספר המכרז,",
    Michrazim6LocalityRetryNumber: 2,
    Michrazim1MichrazRetryNumber:1000,
    Michrazim7FilterByDate: "האם ברצונך לסנן לפי תאריכים?",
    Michrazim8FromDate: "dd/mm/yyyy אנא הזן תאריך התחלה בפורמט",
    Michrazim9ToDate: "dd/mm/yyyy אנא הזן תאריך סיום בפורמט",
    Michrazim10PreResponse: "כמה רגעים בבקשה      ",
    Michrazim10EmptyResponse: "אני מצטערת, לא נמצאו תוצאות, אולי כדאי להרחיב את החיפוש",
    MichrazimResultsLinkButton: "   לתוצאות המכרז ",
    Michrazim10DetailsLinkButton: "לצפייה בפרטי המכרז",
    ResultError: "אני מצטערת, לא מצאנו את מה שחיפשת",
    GenericError: "אופס, משהו השתבש",
    StartOver: "איך אוכל לעזור?",
    unSuccededToNoticeTheLocality:"לא הצלחתי להבין לאיזה ישוב התכוונת. להלן מכרזים העונים לקריטריונים הקודמים שהוזנו ",
    unSuccededToNoticeTheMichraz:" לא הצלחתי להבין לאיזה מכרז התכוונת.להלן מכרזים מהמאגר:"
    // Michrazim1Michraz:"אנא הכנס מספר מכרז בפורמט המבוקש",
    // MichrazNotCorrect2:"המכרז המבוקש לא נמצא, באפשרותך לפנות לעזרה",
}
 